### ISSUE TITLE
Implement a way to merge configuration files together

### ISSUE THREAD

**Issue by halfak** [halfak/yamlconf#3]
```
foo:
  bar:
    val: 1
    type: pants
```

 +

```
foo:
  bar:
    type: hats
```

 ==

```
foo:
  bar:
    val: 1
    type: hats
```
